# Die erste Zeile eines HTTP Requests enthält das Verb: GET/POST/PUT/DELETE.
# Diesem folgt der angefragte Pfad (hier die gesamte URL) und die HTTP Version
POST http://localhost:3000/register HTTP/1.1
Content-Type: application/json
Accept: application/json

# Die Daten, die gesendet werden sollen,
# werden abschließend - getrennt durch eine leere Zeile - angegeben.
{
    "username": "till",
    "password": "geheim"
}


# Die REST Client Extension erlaubt es in einer Datei mehrere Requests anzugeben.
# Dazu können die Requests mit 3 # getrennt werden.

###

# Hier kann der nächste Request stehen
POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "till",
    "password": "geheim"
}

###

POST http://localhost:3000/login HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "username": "till",
    "password": "geheim"
}

###
POST http://localhost:3000/einkaufsliste HTTP/1.1
Content-Type: application/json
Accept: application/json

{
    "name": "einkaufsliste1"
}

###

GET http://localhost:3000/einkaufsliste HTTP/1.1
Content-Type: application/json
Accept: application/json